// GigePreviewer.idl: источник языка IDL для GigePreviewer
//

// Этот файл будет обработан средством MIDL для
// создание библиотеки типов ($handlersafeidlname$.tlb) и кода маршалирования.

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(c1a49bb6-4372-4a35-92ea-7a0f54b41bd1),
	dual,
	nonextensible,
	pointer_default(unique)
]
interface IPreview : IDispatch
{
	[propget, id(1)] HRESULT Radius([out, retval] DOUBLE* pVal);
	[propput, id(1)] HRESULT Radius([in] DOUBLE newVal);
	[id(2)] HRESULT GetArea([out] DOUBLE* Area);
};
[
	uuid(ff68c777-c91e-4f6e-aec0-4a771b607c6c),
	version(1.0),
]
library GigePreviewerLib
{
	importlib("stdole2.tlb");
	[
		uuid(316bc956-842f-4411-9473-e19a9267dd5d)
	]
	coclass Preview
	{
		[default] interface IPreview;
	};
};

import "shobjidl.idl";
